{% set version = "2.7.3" %}

package:
  name: numexpr
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/numexpr/numexpr-{{ version }}.tar.gz
  sha256: 43616529f9b7d1afc83386f943dc66c4da5e052f00217ba7e3ad8dd1b5f3a825

build:
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - mkl-devel
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - numexpr
    - numexpr.interpreter

about:
  home: https://github.com/pydata/numexpr
  license: MIT
  license_file: LICENSE.txt
  summary: Fast numerical expression evaluator for NumPy.
  description: |
    Numexpr is a fast numerical expression evaluator for NumPy. With it,
    expressions that operate on arrays (like "3*a+4*b") are accelerated and use
    less memory than doing the same calculation in Python.
  doc_url: https://github.com/pydata/numexpr/wiki/Numexpr-Users-Guide
  dev_url: https://github.com/pydata/numexpr

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - scopatz
    - djkirkham
