appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: pZ8/mt0e3z/WJkXe8vyNNP8k10L8bZfIf1KyDr8FL23s0FW554MGAAz44EfP6YL3UHrBUE4KTFF46S1UtaSKFLn6+YdEwYOXWMOLrXabpuEM/E1vhACPhbUiNB0jTttnkXtebiVFy1vJok1Sr0gfQ/X293ukqljayMVRWk63aXSo8kZygJwvDjIi8Ml+RbCOOHItWnM+lx5RSvh2o7HFc/LMFiMpl1HooBcSwh1gSMhqFuifvNjLViUDeHm8LtUbCs8sSRIJvMBci5zOtRwXfHOnqfcXzOayuG1CAe9fGkqAeWOC4ay39VuCicAXxnUIdqim668LMBZokss4282xwv8h9zGAD/iolEqkNp/CrynLePt3Hhfxg8FaqbMAvdUbKJT8OzoYerAENA/CW31vAhWcqdCkAAkhBDA1kyZZXBW7IdgG09JE+GLngiiZ1n1Z9fOFxT4v3FEsvCl+dLaf7/zwXXevsVkLDPvWnY13nF2UxbTAzrJDYfx42dd4p86ETCkEU4vZsraGs8JFhxh3I6WWvsAmaEIosqZvJPJb2qqmNwO2BHAjZ8Fqu15irnUivykwclpt3RtSP0etKBfR5aKDHb6v10kJiW4M1URo5NPs5xsvoq5lZ4el/q3VFv3yRG/az10RR/9OwNoqJHMNoU+javi7hbAOJpWob31S78Q=}
provider:
  win: azure
conda_forge_output_validation: true
